var players = [{
        "Player": "David Johnson",
        "Rank": 1,
        "Position": "RB",
        "Team": "ARI",
        "PosRank": "RB1",
        "Bye": 8,
        "MB": 1,
        "MC": 1,
        "TC": 3,
        "EK": 1,
        "FY": 2,
        "AVG": 1.6
    },
    {
        "Player": "LeVeon Bell",
        "Rank": 2,
        "Position": "RB",
        "Team": "PIT",
        "PosRank": "RB2",
        "Bye": 9,
        "MB": 2,
        "MC": 2,
        "TC": 2,
        "EK": 2,
        "FY": 1,
        "AVG": 1.8
    },
    {
        "Player": "Antonio Brown",
        "Rank": 3,
        "Position": "WR",
        "Team": "PIT",
        "PosRank": "WR1",
        "Bye": 9,
        "MB": 3,
        "MC": 3,
        "TC": 1,
        "EK": 3,
        "FY": 3,
        "AVG": 2.6
    },
    {
        "Player": "Odell Beckham Jr.",
        "Rank": 4,
        "Position": "WR",
        "Team": "NYG",
        "PosRank": "WR2",
        "Bye": 8,
        "MB": 6,
        "MC": 5,
        "TC": 6,
        "EK": 4,
        "FY": 5,
        "AVG": 5.2
    },
    {
        "Player": "Julio Jones",
        "Rank": 5,
        "Position": "WR",
        "Team": "ATL",
        "PosRank": "WR3",
        "Bye": 5,
        "MB": 7,
        "MC": 4,
        "TC": 4,
        "EK": 6,
        "FY": 6,
        "AVG": 5.4
    },
    {
        "Player": "Jordy Nelson",
        "Rank": 6,
        "Position": "WR",
        "Team": "GB",
        "PosRank": "WR4",
        "Bye": 8,
        "MB": 4,
        "MC": 7,
        "TC": 5,
        "EK": 7,
        "FY": 11,
        "AVG": 6.8
    },
    {
        "Player": "LeSean McCoy",
        "Rank": 7,
        "Position": "RB",
        "Team": "BUF",
        "PosRank": "RB3",
        "Bye": 6,
        "MB": 5,
        "MC": 10,
        "TC": 7,
        "EK": 9,
        "FY": 4,
        "AVG": 7
    },
    {
        "Player": "Mike Evans",
        "Rank": 8,
        "Position": "WR",
        "Team": "TB",
        "PosRank": "WR5",
        "Bye": 11,
        "MB": 11,
        "MC": 8,
        "TC": 12,
        "EK": 5,
        "FY": 7,
        "AVG": 8.6
    },
    {
        "Player": "A.J. Green",
        "Rank": 9,
        "Position": "WR",
        "Team": "CIN",
        "PosRank": "WR6",
        "Bye": 6,
        "MB": 12,
        "MC": 6,
        "TC": 9,
        "EK": 12,
        "FY": 8,
        "AVG": 9.4
    },
    {
        "Player": "Devonta Freeman",
        "Rank": 10,
        "Position": "RB",
        "Team": "ATL",
        "PosRank": "RB4",
        "Bye": 5,
        "MB": 8,
        "MC": 11,
        "TC": 8,
        "EK": 11,
        "FY": 9,
        "AVG": 9.4
    },
    {
        "Player": "Michael Thomas",
        "Rank": 11,
        "Position": "WR",
        "Team": "NO",
        "PosRank": "WR7",
        "Bye": 5,
        "MB": 14,
        "MC": 9,
        "TC": 10,
        "EK": 8,
        "FY": 12,
        "AVG": 10.6
    },
    {
        "Player": "Melvin Gordon",
        "Rank": 12,
        "Position": "RB",
        "Team": "LAC",
        "PosRank": "RB5",
        "Bye": 9,
        "MB": 9,
        "MC": 12,
        "TC": 11,
        "EK": 10,
        "FY": 13,
        "AVG": 11
    },
    {
        "Player": "Jordan Howard",
        "Rank": 13,
        "Position": "RB",
        "Team": "CHI",
        "PosRank": "RB6",
        "Bye": 9,
        "MB": 13,
        "MC": 13,
        "TC": 17,
        "EK": 14,
        "FY": 10,
        "AVG": 13.4
    },
    {
        "Player": "DeMarco Murray",
        "Rank": 14,
        "Position": "RB",
        "Team": "TEN",
        "PosRank": "RB7",
        "Bye": 8,
        "MB": 10,
        "MC": 20,
        "TC": 14,
        "EK": 15,
        "FY": 16,
        "AVG": 15
    },
    {
        "Player": "Brandin Cooks",
        "Rank": 15,
        "Position": "WR",
        "Team": "NE",
        "PosRank": "WR8",
        "Bye": 9,
        "MB": 16,
        "MC": 16,
        "TC": 15,
        "EK": 13,
        "FY": 15,
        "AVG": 15
    },
    {
        "Player": "Jay Ajayi",
        "Rank": 16,
        "Position": "RB",
        "Team": "MIA",
        "PosRank": "RB8",
        "Bye": 11,
        "MB": 15,
        "MC": 14,
        "TC": 19,
        "EK": 17,
        "FY": 17,
        "AVG": 16.4
    },
    {
        "Player": "Doug Baldwin",
        "Rank": 17,
        "Position": "WR",
        "Team": "SEA",
        "PosRank": "WR9",
        "Bye": 6,
        "MB": 18,
        "MC": 17,
        "TC": 13,
        "EK": 16,
        "FY": 20,
        "AVG": 16.8
    },
    {
        "Player": "Todd Gurley",
        "Rank": 18,
        "Position": "RB",
        "Team": "LAR",
        "PosRank": "RB9",
        "Bye": 8,
        "MB": 26,
        "MC": 19,
        "TC": 16,
        "EK": 18,
        "FY": 21,
        "AVG": 20
    },
    {
        "Player": "T.Y. Hilton",
        "Rank": 19,
        "Position": "WR",
        "Team": "IND",
        "PosRank": "WR10",
        "Bye": 11,
        "MB": 29,
        "MC": 15,
        "TC": 23,
        "EK": 19,
        "FY": 19,
        "AVG": 21
    },
    {
        "Player": "Dez Bryant",
        "Rank": 20,
        "Position": "WR",
        "Team": "DAL",
        "PosRank": "WR11",
        "Bye": 6,
        "MB": 17,
        "MC": 23,
        "TC": 27,
        "EK": 31,
        "FY": 14,
        "AVG": 22.4
    },
    {
        "Player": "Rob Gronkowski",
        "Rank": 21,
        "Position": "TE",
        "Team": "NE",
        "PosRank": "TE1",
        "Bye": 9,
        "MB": 19,
        "MC": 24,
        "TC": 18,
        "EK": 32,
        "FY": 22,
        "AVG": 23
    },
    {
        "Player": "Amari Cooper",
        "Rank": 22,
        "Position": "WR",
        "Team": "OAK",
        "PosRank": "WR12",
        "Bye": 10,
        "MB": 33,
        "MC": 22,
        "TC": 24,
        "EK": 20,
        "FY": 18,
        "AVG": 23.4
    },
    {
        "Player": "Leonard Fournette",
        "Rank": 23,
        "Position": "RB",
        "Team": "JAC",
        "PosRank": "RB10",
        "Bye": 8,
        "MB": 20,
        "MC": 21,
        "TC": 29,
        "EK": 25,
        "FY": 24,
        "AVG": 23.8
    },
    {
        "Player": "Demaryius Thomas",
        "Rank": 24,
        "Position": "WR",
        "Team": "DEN",
        "PosRank": "WR13",
        "Bye": 5,
        "MB": 34,
        "MC": 25,
        "TC": 26,
        "EK": 21,
        "FY": 27,
        "AVG": 26.6
    },
    {
        "Player": "Lamar Miller",
        "Rank": 25,
        "Position": "RB",
        "Team": "HOU",
        "PosRank": "RB11",
        "Bye": 7,
        "MB": 30,
        "MC": 31,
        "TC": 25,
        "EK": 23,
        "FY": 29,
        "AVG": 27.6
    },
    {
        "Player": "Terrelle Pryor Sr.",
        "Rank": 26,
        "Position": "WR",
        "Team": "WAS",
        "PosRank": "WR14",
        "Bye": 5,
        "MB": 31,
        "MC": 26,
        "TC": 36,
        "EK": 22,
        "FY": 23,
        "AVG": 27.6
    },
    {
        "Player": "Alshon Jeffery",
        "Rank": 27,
        "Position": "WR",
        "Team": "PHI",
        "PosRank": "WR15",
        "Bye": 10,
        "MB": 22,
        "MC": 27,
        "TC": 28,
        "EK": 35,
        "FY": 28,
        "AVG": 28
    },
    {
        "Player": "DeAndre Hopkins",
        "Rank": 28,
        "Position": "WR",
        "Team": "HOU",
        "PosRank": "WR16",
        "Bye": 7,
        "MB": 40,
        "MC": 18,
        "TC": 21,
        "EK": 34,
        "FY": 33,
        "AVG": 29.2
    },
    {
        "Player": "Isaiah Crowell",
        "Rank": 29,
        "Position": "RB",
        "Team": "CLE",
        "PosRank": "RB12",
        "Bye": 9,
        "MB": 23,
        "MC": 41,
        "TC": 22,
        "EK": 24,
        "FY": 39,
        "AVG": 29.8
    },
    {
        "Player": "Ezekiel Elliott",
        "Rank": 30,
        "Position": "RB",
        "Team": "DAL",
        "PosRank": "RB13",
        "Bye": 6,
        "MB": 28,
        "MC": 29,
        "TC": 20,
        "EK": 41,
        "FY": 38,
        "AVG": 31.2
    },
    {
        "Player": "Michael Crabtree",
        "Rank": 31,
        "Position": "WR",
        "Team": "OAK",
        "PosRank": "WR17",
        "Bye": 10,
        "MB": 36,
        "MC": 28,
        "TC": 37,
        "EK": 30,
        "FY": 32,
        "AVG": 32.6
    },
    {
        "Player": "Keenan Allen",
        "Rank": 32,
        "Position": "WR",
        "Team": "LAC",
        "PosRank": "WR18",
        "Bye": 9,
        "MB": 21,
        "MC": 33,
        "TC": 58,
        "EK": 36,
        "FY": 26,
        "AVG": 34.8
    },
    {
        "Player": "Golden Tate",
        "Rank": 33,
        "Position": "WR",
        "Team": "DET",
        "PosRank": "WR19",
        "Bye": 7,
        "MB": 37,
        "MC": 38,
        "TC": 32,
        "EK": 37,
        "FY": 41,
        "AVG": 37
    },
    {
        "Player": "Kareem Hunt",
        "Rank": 34,
        "Position": "RB",
        "Team": "KC",
        "PosRank": "RB14",
        "Bye": 10,
        "MB": 27,
        "MC": 42,
        "TC": 39,
        "EK": 27,
        "FY": 50,
        "AVG": 37
    },
    {
        "Player": "Christian McCaffrey",
        "Rank": 35,
        "Position": "RB",
        "Team": "CAR",
        "PosRank": "RB15",
        "Bye": 11,
        "MB": 32,
        "MC": 43,
        "TC": 33,
        "EK": 26,
        "FY": 56,
        "AVG": 38
    },
    {
        "Player": "Marshawn Lynch",
        "Rank": 36,
        "Position": "RB",
        "Team": "OAK",
        "PosRank": "RB16",
        "Bye": 10,
        "MB": 25,
        "MC": 30,
        "TC": 34,
        "EK": 52,
        "FY": 55,
        "AVG": 39.2
    },
    {
        "Player": "Larry Fitzgerald",
        "Rank": 37,
        "Position": "WR",
        "Team": "ARI",
        "PosRank": "WR20",
        "Bye": 8,
        "MB": 45,
        "MC": 37,
        "TC": 47,
        "EK": 33,
        "FY": 36,
        "AVG": 39.6
    },
    {
        "Player": "Carlos Hyde",
        "Rank": 38,
        "Position": "RB",
        "Team": "SF",
        "PosRank": "RB17",
        "Bye": 11,
        "MB": 62,
        "MC": 32,
        "TC": 31,
        "EK": 44,
        "FY": 35,
        "AVG": 40.8
    },
    {
        "Player": "Ty Montgomery",
        "Rank": 39,
        "Position": "RB",
        "Team": "GB",
        "PosRank": "RB18",
        "Bye": 8,
        "MB": 43,
        "MC": 65,
        "TC": 30,
        "EK": 42,
        "FY": 25,
        "AVG": 41
    },
    {
        "Player": "Dalvin Cook",
        "Rank": 40,
        "Position": "RB",
        "Team": "MIN",
        "PosRank": "RB19",
        "Bye": 9,
        "MB": 54,
        "MC": 44,
        "TC": 35,
        "EK": 28,
        "FY": 46,
        "AVG": 41.4
    },
    {
        "Player": "Jordan Reed",
        "Rank": 41,
        "Position": "TE",
        "Team": "WAS",
        "PosRank": "TE2",
        "Bye": 5,
        "MB": 24,
        "MC": 55,
        "TC": 44,
        "EK": 47,
        "FY": 43,
        "AVG": 42.6
    },
    {
        "Player": "Davante Adams",
        "Rank": 42,
        "Position": "WR",
        "Team": "GB",
        "PosRank": "WR21",
        "Bye": 8,
        "MB": 35,
        "MC": 36,
        "TC": 61,
        "EK": 38,
        "FY": 51,
        "AVG": 44.2
    },
    {
        "Player": "Emmanuel Sanders",
        "Rank": 43,
        "Position": "WR",
        "Team": "DEN",
        "PosRank": "WR22",
        "Bye": 5,
        "MB": 46,
        "MC": 34,
        "TC": 42,
        "EK": 56,
        "FY": 47,
        "AVG": 45
    },
    {
        "Player": "Jarvis Landry",
        "Rank": 44,
        "Position": "WR",
        "Team": "MIA",
        "PosRank": "WR23",
        "Bye": 11,
        "MB": 61,
        "MC": 45,
        "TC": 49,
        "EK": 40,
        "FY": 31,
        "AVG": 45.2
    },
    {
        "Player": "Tom Brady",
        "Rank": 45,
        "Position": "QB",
        "Team": "NE",
        "PosRank": "QB1",
        "Bye": 9,
        "MB": 39,
        "MC": 49,
        "TC": 50,
        "EK": 49,
        "FY": 40,
        "AVG": 45.4
    },
    {
        "Player": "Aaron Rodgers",
        "Rank": 46,
        "Position": "QB",
        "Team": "GB",
        "PosRank": "QB2",
        "Bye": 8,
        "MB": 47,
        "MC": 48,
        "TC": 41,
        "EK": 48,
        "FY": 45,
        "AVG": 45.8
    },
    {
        "Player": "Danny Woodhead",
        "Rank": 47,
        "Position": "RB",
        "Team": "BAL",
        "PosRank": "RB20",
        "Bye": 10,
        "MB": 49,
        "MC": 66,
        "TC": 43,
        "EK": 51,
        "FY": 30,
        "AVG": 47.8
    },
    {
        "Player": "Travis Kelce",
        "Rank": 48,
        "Position": "TE",
        "Team": "KC",
        "PosRank": "TE3",
        "Bye": 10,
        "MB": 60,
        "MC": 56,
        "TC": 46,
        "EK": 45,
        "FY": 34,
        "AVG": 48.2
    },
    {
        "Player": "Jamison Crowder",
        "Rank": 49,
        "Position": "WR",
        "Team": "WAS",
        "PosRank": "WR24",
        "Bye": 5,
        "MB": 44,
        "MC": 51,
        "TC": 56,
        "EK": 39,
        "FY": 52,
        "AVG": 48.4
    },
    {
        "Player": "Bilal Powell",
        "Rank": 50,
        "Position": "RB",
        "Team": "NYJ",
        "PosRank": "RB21",
        "Bye": 11,
        "MB": 50,
        "MC": 58,
        "TC": 38,
        "EK": 43,
        "FY": 54,
        "AVG": 48.6
    },
    {
        "Player": "Kelvin Benjamin",
        "Rank": 51,
        "Position": "WR",
        "Team": "CAR",
        "PosRank": "WR25",
        "Bye": 11,
        "MB": 41,
        "MC": 40,
        "TC": 60,
        "EK": 60,
        "FY": 42,
        "AVG": 48.6
    },
    {
        "Player": "Allen Robinson",
        "Rank": 52,
        "Position": "WR",
        "Team": "JAC",
        "PosRank": "WR26",
        "Bye": 8,
        "MB": 53,
        "MC": 35,
        "TC": 48,
        "EK": 59,
        "FY": 53,
        "AVG": 49.6
    },
    {
        "Player": "Tyreek Hill",
        "Rank": 53,
        "Position": "WR",
        "Team": "KC",
        "PosRank": "WR27",
        "Bye": 10,
        "MB": 42,
        "MC": 46,
        "TC": 66,
        "EK": 57,
        "FY": 49,
        "AVG": 52
    },
    {
        "Player": "Joe Mixon",
        "Rank": 54,
        "Position": "RB",
        "Team": "CIN",
        "PosRank": "RB22",
        "Bye": 6,
        "MB": 64,
        "MC": 67,
        "TC": 45,
        "EK": 29,
        "FY": 60,
        "AVG": 53
    },
    {
        "Player": "Greg Olsen",
        "Rank": 55,
        "Position": "TE",
        "Team": "CAR",
        "PosRank": "TE4",
        "Bye": 11,
        "MB": 70,
        "MC": 54,
        "TC": 51,
        "EK": 46,
        "FY": 44,
        "AVG": 53
    },
    {
        "Player": "Sammy Watkins",
        "Rank": 56,
        "Position": "WR",
        "Team": "LAR",
        "PosRank": "WR28",
        "Bye": 8,
        "MB": 57,
        "MC": 39,
        "TC": 55,
        "EK": 67,
        "FY": 48,
        "AVG": 53.2
    },
    {
        "Player": "Drew Brees",
        "Rank": 57,
        "Position": "QB",
        "Team": "NO",
        "PosRank": "QB3",
        "Bye": 5,
        "MB": 56,
        "MC": 57,
        "TC": 54,
        "EK": 50,
        "FY": 62,
        "AVG": 55.8
    },
    {
        "Player": "Pierre Garcon",
        "Rank": 58,
        "Position": "WR",
        "Team": "SF",
        "PosRank": "WR29",
        "Bye": 11,
        "MB": 48,
        "MC": 61,
        "TC": 71,
        "EK": 70,
        "FY": 37,
        "AVG": 57.4
    },
    {
        "Player": "Stefon Diggs",
        "Rank": 59,
        "Position": "WR",
        "Team": "MIN",
        "PosRank": "WR30",
        "Bye": 9,
        "MB": 59,
        "MC": 47,
        "TC": 67,
        "EK": 61,
        "FY": 57,
        "AVG": 58.2
    },
    {
        "Player": "Mark Ingram",
        "Rank": 60,
        "Position": "RB",
        "Team": "NO",
        "PosRank": "RB23",
        "Bye": 5,
        "MB": 69,
        "MC": 59,
        "TC": 40,
        "EK": 54,
        "FY": 69,
        "AVG": 58.2
    },
    {
        "Player": "Martavis Bryant",
        "Rank": 61,
        "Position": "WR",
        "Team": "PIT",
        "PosRank": "WR31",
        "Bye": 9,
        "MB": 51,
        "MC": 53,
        "TC": 62,
        "EK": 68,
        "FY": 64,
        "AVG": 59.6
    },
    {
        "Player": "Frank Gore",
        "Rank": 62,
        "Position": "RB",
        "Team": "IND",
        "PosRank": "RB24",
        "Bye": 11,
        "MB": 79,
        "MC": 68,
        "TC": 53,
        "EK": 53,
        "FY": 59,
        "AVG": 62.4
    },
    {
        "Player": "Brandon Marshall",
        "Rank": 63,
        "Position": "WR",
        "Team": "NYG",
        "PosRank": "WR32",
        "Bye": 8,
        "MB": 38,
        "MC": 81,
        "TC": 77,
        "EK": 58,
        "FY": 58,
        "AVG": 62.4
    },
    {
        "Player": "DeVante Parker",
        "Rank": 64,
        "Position": "WR",
        "Team": "MIA",
        "PosRank": "WR33",
        "Bye": 11,
        "MB": 63,
        "MC": 52,
        "TC": 76,
        "EK": 72,
        "FY": 65,
        "AVG": 65.6
    },
    {
        "Player": "Mike Gillislee",
        "Rank": 65,
        "Position": "RB",
        "Team": "NE",
        "PosRank": "RB25",
        "Bye": 9,
        "MB": 81,
        "MC": 76,
        "TC": 65,
        "EK": 55,
        "FY": 61,
        "AVG": 67.6
    },
    {
        "Player": "Theo Riddick",
        "Rank": 66,
        "Position": "RB",
        "Team": "DET",
        "PosRank": "RB26",
        "Bye": 7,
        "MB": 86,
        "MC": 69,
        "TC": 52,
        "EK": 73,
        "FY": 66,
        "AVG": 69.2
    },
    {
        "Player": "Adrian Peterson",
        "Rank": 67,
        "Position": "RB",
        "Team": "NO",
        "PosRank": "RB27",
        "Bye": 5,
        "MB": 55,
        "MC": 74,
        "TC": 78,
        "EK": 65,
        "FY": 76,
        "AVG": 69.6
    },
    {
        "Player": "Willie Snead",
        "Rank": 68,
        "Position": "WR",
        "Team": "NO",
        "PosRank": "WR34",
        "Bye": 5,
        "MB": 58,
        "MC": 50,
        "TC": 74,
        "EK": 84,
        "FY": 89,
        "AVG": 71
    },
    {
        "Player": "Matt Ryan",
        "Rank": 69,
        "Position": "QB",
        "Team": "ATL",
        "PosRank": "QB4",
        "Bye": 5,
        "MB": 65,
        "MC": 60,
        "TC": 68,
        "EK": 91,
        "FY": 72,
        "AVG": 71.2
    },
    {
        "Player": "Rob Kelley",
        "Rank": 70,
        "Position": "RB",
        "Team": "WAS",
        "PosRank": "RB28",
        "Bye": 5,
        "MB": 71,
        "MC": 78,
        "TC": 84,
        "EK": 62,
        "FY": 63,
        "AVG": 71.6
    },
    {
        "Player": "Ameer Abdullah",
        "Rank": 71,
        "Position": "RB",
        "Team": "DET",
        "PosRank": "RB29",
        "Bye": 7,
        "MB": 82,
        "MC": 71,
        "TC": 57,
        "EK": 74,
        "FY": 80,
        "AVG": 72.8
    },
    {
        "Player": "Paul Perkins",
        "Rank": 72,
        "Position": "RB",
        "Team": "NYG",
        "PosRank": "RB30",
        "Bye": 8,
        "MB": 74,
        "MC": 75,
        "TC": 69,
        "EK": 63,
        "FY": 86,
        "AVG": 73.4
    },
    {
        "Player": "C.J. Anderson",
        "Rank": 73,
        "Position": "RB",
        "Team": "DEN",
        "PosRank": "RB31",
        "Bye": 5,
        "MB": 94,
        "MC": 72,
        "TC": 75,
        "EK": 64,
        "FY": 74,
        "AVG": 75.8
    },
    {
        "Player": "Jeremy Maclin",
        "Rank": 74,
        "Position": "WR",
        "Team": "BAL",
        "PosRank": "WR35",
        "Bye": 10,
        "MB": 66,
        "MC": 79,
        "TC": 87,
        "EK": 87,
        "FY": 71,
        "AVG": 78
    },
    {
        "Player": "Eric Decker",
        "Rank": 75,
        "Position": "WR",
        "Team": "TEN",
        "PosRank": "WR36",
        "Bye": 8,
        "MB": 52,
        "MC": 88,
        "TC": 91,
        "EK": 88,
        "FY": 81,
        "AVG": 80
    },
    {
        "Player": "DeSean Jackson",
        "Rank": 76,
        "Position": "WR",
        "Team": "TB",
        "PosRank": "WR37",
        "Bye": 11,
        "MB": 103,
        "MC": 82,
        "TC": 86,
        "EK": 69,
        "FY": 68,
        "AVG": 81.6
    },
    {
        "Player": "Terrance West",
        "Rank": 77,
        "Position": "RB",
        "Team": "BAL",
        "PosRank": "RB32",
        "Bye": 10,
        "MB": 75,
        "MC": 77,
        "TC": 63,
        "EK": 78,
        "FY": 115,
        "AVG": 81.6
    },
    {
        "Player": "Duke Johnson Jr.",
        "Rank": 78,
        "Position": "RB",
        "Team": "CLE",
        "PosRank": "RB33",
        "Bye": 9,
        "MB": 101,
        "MC": 73,
        "TC": 64,
        "EK": 77,
        "FY": 103,
        "AVG": 83.6
    },
    {
        "Player": "Jimmy Graham",
        "Rank": 79,
        "Position": "TE",
        "Team": "SEA",
        "PosRank": "TE5",
        "Bye": 6,
        "MB": 91,
        "MC": 63,
        "TC": 70,
        "EK": 102,
        "FY": 97,
        "AVG": 84.6
    },
    {
        "Player": "Mike Wallace",
        "Rank": 80,
        "Position": "WR",
        "Team": "BAL",
        "PosRank": "WR38",
        "Bye": 10,
        "MB": 77,
        "MC": 86,
        "TC": 94,
        "EK": 90,
        "FY": 79,
        "AVG": 85.2
    },
    {
        "Player": "Russell Wilson",
        "Rank": 81,
        "Position": "QB",
        "Team": "SEA",
        "PosRank": "QB5",
        "Bye": 6,
        "MB": 67,
        "MC": 99,
        "TC": 73,
        "EK": 92,
        "FY": 95,
        "AVG": 85.2
    },
    {
        "Player": "Donte Moncrief",
        "Rank": 82,
        "Position": "WR",
        "Team": "IND",
        "PosRank": "WR39",
        "Bye": 11,
        "MB": 73,
        "MC": 80,
        "TC": 80,
        "EK": 86,
        "FY": 108,
        "AVG": 85.4
    },
    {
        "Player": "Kenny Britt",
        "Rank": 83,
        "Position": "WR",
        "Team": "CLE",
        "PosRank": "WR40",
        "Bye": 9,
        "MB": 100,
        "MC": 85,
        "TC": 89,
        "EK": 71,
        "FY": 82,
        "AVG": 85.4
    },
    {
        "Player": "Adam Thielen",
        "Rank": 84,
        "Position": "WR",
        "Team": "MIN",
        "PosRank": "WR41",
        "Bye": 9,
        "MB": 80,
        "MC": 87,
        "TC": 83,
        "EK": 89,
        "FY": 99,
        "AVG": 87.6
    },
    {
        "Player": "Eddie Lacy",
        "Rank": 85,
        "Position": "RB",
        "Team": "SEA",
        "PosRank": "RB34",
        "Bye": 6,
        "MB": 96,
        "MC": 84,
        "TC": 109,
        "EK": 79,
        "FY": 78,
        "AVG": 89.2
    },
    {
        "Player": "Tevin Coleman",
        "Rank": 86,
        "Position": "RB",
        "Team": "ATL",
        "PosRank": "RB35",
        "Bye": 5,
        "MB": 98,
        "MC": 102,
        "TC": 72,
        "EK": 75,
        "FY": 102,
        "AVG": 89.8
    },
    {
        "Player": "Delanie Walker",
        "Rank": 87,
        "Position": "TE",
        "Team": "TEN",
        "PosRank": "TE6",
        "Bye": 8,
        "MB": 95,
        "MC": 92,
        "TC": 88,
        "EK": 101,
        "FY": 73,
        "AVG": 89.8
    },
    {
        "Player": "Kyle Rudolph",
        "Rank": 88,
        "Position": "TE",
        "Team": "MIN",
        "PosRank": "TE7",
        "Bye": 9,
        "MB": 93,
        "MC": 62,
        "TC": 59,
        "EK": 126,
        "FY": 110,
        "AVG": 90
    },
    {
        "Player": "Tyrell Williams",
        "Rank": 89,
        "Position": "WR",
        "Team": "LAC",
        "PosRank": "WR42",
        "Bye": 9,
        "MB": 99,
        "MC": 89,
        "TC": 95,
        "EK": 66,
        "FY": 101,
        "AVG": 90
    },
    {
        "Player": "James White",
        "Rank": 90,
        "Position": "RB",
        "Team": "NE",
        "PosRank": "RB36",
        "Bye": 9,
        "MB": 72,
        "MC": 116,
        "TC": 85,
        "EK": 105,
        "FY": 77,
        "AVG": 91
    },
    {
        "Player": "Matt Forte",
        "Rank": 91,
        "Position": "RB",
        "Team": "NYJ",
        "PosRank": "RB37",
        "Bye": 11,
        "MB": 83,
        "MC": 105,
        "TC": 82,
        "EK": 103,
        "FY": 85,
        "AVG": 91.6
    },
    {
        "Player": "Kirk Cousins",
        "Rank": 92,
        "Position": "QB",
        "Team": "WAS",
        "PosRank": "QB6",
        "Bye": 5,
        "MB": 68,
        "MC": 100,
        "TC": 92,
        "EK": 94,
        "FY": 104,
        "AVG": 91.6
    },
    {
        "Player": "Darren McFadden",
        "Rank": 93,
        "Position": "RB",
        "Team": "DAL",
        "PosRank": "RB38",
        "Bye": 6,
        "MB": 88,
        "MC": 103,
        "TC": 93,
        "EK": 82,
        "FY": 96,
        "AVG": 92.4
    },
    {
        "Player": "Cam Newton",
        "Rank": 94,
        "Position": "QB",
        "Team": "CAR",
        "PosRank": "QB7",
        "Bye": 11,
        "MB": 104,
        "MC": 70,
        "TC": 81,
        "EK": 93,
        "FY": 114,
        "AVG": 92.4
    },
    {
        "Player": "Doug Martin",
        "Rank": 95,
        "Position": "RB",
        "Team": "TB",
        "PosRank": "RB39",
        "Bye": 11,
        "MB": 78,
        "MC": 104,
        "TC": 117,
        "EK": 83,
        "FY": 105,
        "AVG": 97.4
    },
    {
        "Player": "Zach Ertz",
        "Rank": 96,
        "Position": "TE",
        "Team": "PHI",
        "PosRank": "TE8",
        "Bye": 10,
        "MB": 128,
        "MC": 64,
        "TC": 79,
        "EK": 127,
        "FY": 92,
        "AVG": 98
    },
    {
        "Player": "Randall Cobb",
        "Rank": 97,
        "Position": "WR",
        "Team": "GB",
        "PosRank": "WR43",
        "Bye": 8,
        "MB": 112,
        "MC": 83,
        "TC": 96,
        "EK": 109,
        "FY": 100,
        "AVG": 100
    },
    {
        "Player": "Chris Hogan",
        "Rank": 98,
        "Position": "WR",
        "Team": "NE",
        "PosRank": "WR44",
        "Bye": 9,
        "MB": 92,
        "MC": 98,
        "TC": 111,
        "EK": 115,
        "FY": 88,
        "AVG": 100.8
    },
    {
        "Player": "Rishard Matthews",
        "Rank": 99,
        "Position": "WR",
        "Team": "TEN",
        "PosRank": "WR45",
        "Bye": 8,
        "MB": 108,
        "MC": 96,
        "TC": 123,
        "EK": 85,
        "FY": 93,
        "AVG": 101
    },
    {
        "Player": "Jonathan Stewart",
        "Rank": 100,
        "Position": "RB",
        "Team": "CAR",
        "PosRank": "RB40",
        "Bye": 11,
        "MB": 106,
        "MC": 117,
        "TC": 101,
        "EK": 80,
        "FY": 107,
        "AVG": 102.2
    },
    {
        "Player": "Darren Sproles",
        "Rank": 101,
        "Position": "RB",
        "Team": "PHI",
        "PosRank": "RB41",
        "Bye": 10,
        "MB": 107,
        "MC": 107,
        "TC": 90,
        "EK": 118,
        "FY": 94,
        "AVG": 103.2
    },
    {
        "Player": "Andrew Luck",
        "Rank": 102,
        "Position": "QB",
        "Team": "IND",
        "PosRank": "QB8",
        "Bye": 11,
        "MB": 84,
        "MC": 109,
        "TC": 104,
        "EK": 95,
        "FY": 133,
        "AVG": 105
    },
    {
        "Player": "LeGarrette Blount",
        "Rank": 103,
        "Position": "RB",
        "Team": "PHI",
        "PosRank": "RB42",
        "Bye": 10,
        "MB": 87,
        "MC": 135,
        "TC": 162,
        "EK": 81,
        "FY": 67,
        "AVG": 106.4
    },
    {
        "Player": "Thomas Rawls",
        "Rank": 104,
        "Position": "RB",
        "Team": "SEA",
        "PosRank": "RB43",
        "Bye": 6,
        "MB": 97,
        "MC": 126,
        "TC": 120,
        "EK": 119,
        "FY": 70,
        "AVG": 106.4
    },
    {
        "Player": "Giovani Bernard",
        "Rank": 105,
        "Position": "RB",
        "Team": "CIN",
        "PosRank": "RB44",
        "Bye": 6,
        "MB": 118,
        "MC": 106,
        "TC": 112,
        "EK": 117,
        "FY": 87,
        "AVG": 108
    },
    {
        "Player": "Corey Coleman",
        "Rank": 106,
        "Position": "WR",
        "Team": "CLE",
        "PosRank": "WR46",
        "Bye": 9,
        "MB": 113,
        "MC": 112,
        "TC": 98,
        "EK": 116,
        "FY": 109,
        "AVG": 109.6
    },
    {
        "Player": "Jordan Matthews",
        "Rank": 107,
        "Position": "WR",
        "Team": "BUF",
        "PosRank": "WR47",
        "Bye": 6,
        "MB": 76,
        "MC": 95,
        "TC": 103,
        "EK": "NR",
        "FY": 75,
        "AVG": 110
    },
    {
        "Player": "Dak Prescott",
        "Rank": 108,
        "Position": "QB",
        "Team": "DAL",
        "PosRank": "QB9",
        "Bye": 6,
        "MB": 121,
        "MC": 114,
        "TC": 119,
        "EK": 99,
        "FY": 98,
        "AVG": 110.2
    },
    {
        "Player": "Zay Jones",
        "Rank": 109,
        "Position": "WR",
        "Team": "BUF",
        "PosRank": "WR48",
        "Bye": 6,
        "MB": 102,
        "MC": 121,
        "TC": 134,
        "EK": 107,
        "FY": 90,
        "AVG": 110.8
    },
    {
        "Player": "Tyler Eifert",
        "Rank": 110,
        "Position": "TE",
        "Team": "CIN",
        "PosRank": "TE9",
        "Bye": 6,
        "MB": 114,
        "MC": 108,
        "TC": 125,
        "EK": 130,
        "FY": 91,
        "AVG": 113.6
    },
    {
        "Player": "C.J. Prosise",
        "Rank": 111,
        "Position": "RB",
        "Team": "SEA",
        "PosRank": "RB45",
        "Bye": 6,
        "MB": 117,
        "MC": 162,
        "TC": 99,
        "EK": 76,
        "FY": 118,
        "AVG": 114.4
    },
    {
        "Player": "Jacquizz Rodgers",
        "Rank": 112,
        "Position": "RB",
        "Team": "TB",
        "PosRank": "RB46",
        "Bye": 11,
        "MB": 115,
        "MC": 119,
        "TC": 132,
        "EK": 104,
        "FY": 113,
        "AVG": 116.6
    },
    {
        "Player": "Jameis Winston",
        "Rank": 113,
        "Position": "QB",
        "Team": "TB",
        "PosRank": "QB10",
        "Bye": 11,
        "MB": 120,
        "MC": 115,
        "TC": 102,
        "EK": 97,
        "FY": 149,
        "AVG": 116.6
    },
    {
        "Player": "Marcus Mariota",
        "Rank": 114,
        "Position": "QB",
        "Team": "TEN",
        "PosRank": "QB11",
        "Bye": 8,
        "MB": 85,
        "MC": 131,
        "TC": 110,
        "EK": 100,
        "FY": 163,
        "AVG": 117.8
    },
    {
        "Player": "Derek Carr",
        "Rank": 115,
        "Position": "QB",
        "Team": "OAK",
        "PosRank": "QB12",
        "Bye": 10,
        "MB": 119,
        "MC": 130,
        "TC": 114,
        "EK": 96,
        "FY": 134,
        "AVG": 118.6
    },
    {
        "Player": "Corey Davis",
        "Rank": 116,
        "Position": "WR",
        "Team": "TEN",
        "PosRank": "WR49",
        "Bye": 8,
        "MB": 111,
        "MC": 90,
        "TC": 113,
        "EK": 110,
        "FY": 170,
        "AVG": 118.8
    },
    {
        "Player": "Kevin White",
        "Rank": 117,
        "Position": "WR",
        "Team": "CHI",
        "PosRank": "WR50",
        "Bye": 9,
        "MB": 124,
        "MC": 91,
        "TC": 121,
        "EK": 177,
        "FY": 83,
        "AVG": 119.2
    },
    {
        "Player": "Matthew Stafford",
        "Rank": 118,
        "Position": "QB",
        "Team": "DET",
        "PosRank": "QB13",
        "Bye": 7,
        "MB": 174,
        "MC": 101,
        "TC": 97,
        "EK": 98,
        "FY": 138,
        "AVG": 121.6
    },
    {
        "Player": "John Brown",
        "Rank": 119,
        "Position": "WR",
        "Team": "ARI",
        "PosRank": "WR51",
        "Bye": 8,
        "MB": 123,
        "MC": 93,
        "TC": 108,
        "EK": 180,
        "FY": 112,
        "AVG": 123.2
    },
    {
        "Player": "Ted Ginn Jr.",
        "Rank": 120,
        "Position": "WR",
        "Team": "NO",
        "PosRank": "WR52",
        "Bye": 5,
        "MB": 90,
        "MC": 97,
        "TC": 118,
        "EK": "NR",
        "FY": 117,
        "AVG": 124.6
    },
    {
        "Player": "Chris Thompson",
        "Rank": 121,
        "Position": "RB",
        "Team": "WAS",
        "PosRank": "RB47",
        "Bye": 5,
        "MB": 136,
        "MC": 129,
        "TC": 106,
        "EK": 121,
        "FY": 137,
        "AVG": 125.8
    },
    {
        "Player": "Derrick Henry",
        "Rank": 122,
        "Position": "RB",
        "Team": "TEN",
        "PosRank": "RB48",
        "Bye": 8,
        "MB": 140,
        "MC": 118,
        "TC": 128,
        "EK": 106,
        "FY": 161,
        "AVG": 130.6
    },
    {
        "Player": "Danny Amendola",
        "Rank": 123,
        "Position": "WR",
        "Team": "NE",
        "PosRank": "WR53",
        "Bye": 9,
        "MB": 89,
        "MC": 163,
        "TC": 167,
        "EK": 114,
        "FY": 127,
        "AVG": 132
    },
    {
        "Player": "Hunter Henry",
        "Rank": 124,
        "Position": "TE",
        "Team": "LAC",
        "PosRank": "TE10",
        "Bye": 9,
        "MB": 135,
        "MC": 140,
        "TC": 138,
        "EK": 128,
        "FY": 130,
        "AVG": 134.2
    },
    {
        "Player": "Josh Doctson",
        "Rank": 125,
        "Position": "WR",
        "Team": "WAS",
        "PosRank": "WR54",
        "Bye": 5,
        "MB": 109,
        "MC": 124,
        "TC": 127,
        "EK": 111,
        "FY": "NR",
        "AVG": 134.4
    },
    {
        "Player": "Martellus Bennett",
        "Rank": 126,
        "Position": "TE",
        "Team": "GB",
        "PosRank": "TE11",
        "Bye": 8,
        "MB": "NR",
        "MC": 133,
        "TC": 100,
        "EK": 129,
        "FY": 111,
        "AVG": 134.8
    },
    {
        "Player": "Ben Roethlisberger",
        "Rank": 127,
        "Position": "QB",
        "Team": "PIT",
        "PosRank": "QB14",
        "Bye": 9,
        "MB": 173,
        "MC": 132,
        "TC": 107,
        "EK": 134,
        "FY": 135,
        "AVG": 136.2
    },
    {
        "Player": "Rex Burkhead",
        "Rank": 128,
        "Position": "RB",
        "Team": "NE",
        "PosRank": "RB49",
        "Bye": 9,
        "MB": 132,
        "MC": 122,
        "TC": 170,
        "EK": 162,
        "FY": 106,
        "AVG": 138.4
    },
    {
        "Player": "Broncos D/ST",
        "Rank": 129,
        "Position": "DST",
        "Team": "DEN",
        "PosRank": "D/ST1",
        "Bye": 5,
        "MB": 141,
        "MC": 142,
        "TC": 133,
        "EK": 139,
        "FY": 140,
        "AVG": 139
    },
    {
        "Player": "Marvin Jones Jr.",
        "Rank": 130,
        "Position": "WR",
        "Team": "DET",
        "PosRank": "WR55",
        "Bye": 7,
        "MB": 185,
        "MC": 94,
        "TC": 105,
        "EK": 113,
        "FY": "NR",
        "AVG": 139.6
    },
    {
        "Player": "Seahawks D/ST",
        "Rank": 131,
        "Position": "DST",
        "Team": "SEA",
        "PosRank": "D/ST2",
        "Bye": 6,
        "MB": 142,
        "MC": 141,
        "TC": 140,
        "EK": 140,
        "FY": 142,
        "AVG": 141
    },
    {
        "Player": "Jack Doyle",
        "Rank": 132,
        "Position": "TE",
        "Team": "IND",
        "PosRank": "TE12",
        "Bye": 11,
        "MB": 129,
        "MC": 164,
        "TC": 161,
        "EK": 131,
        "FY": 132,
        "AVG": 143.4
    },
    {
        "Player": "Chiefs D/ST",
        "Rank": 133,
        "Position": "DST",
        "Team": "KC",
        "PosRank": "D/ST3",
        "Bye": 10,
        "MB": 146,
        "MC": 144,
        "TC": 144,
        "EK": 141,
        "FY": 144,
        "AVG": 143.8
    },
    {
        "Player": "Texans D/ST",
        "Rank": 134,
        "Position": "DST",
        "Team": "HOU",
        "PosRank": "D/ST4",
        "Bye": 7,
        "MB": 144,
        "MC": 143,
        "TC": 143,
        "EK": 142,
        "FY": 147,
        "AVG": 143.8
    },
    {
        "Player": "Vikings D/ST",
        "Rank": 135,
        "Position": "DST",
        "Team": "MIN",
        "PosRank": "D/ST5",
        "Bye": 9,
        "MB": 147,
        "MC": 145,
        "TC": 146,
        "EK": 144,
        "FY": 143,
        "AVG": 145
    },
    {
        "Player": "Latavius Murray",
        "Rank": 136,
        "Position": "RB",
        "Team": "MIN",
        "PosRank": "RB50",
        "Bye": 9,
        "MB": 138,
        "MC": 170,
        "TC": 193,
        "EK": 123,
        "FY": 116,
        "AVG": 148
    },
    {
        "Player": "Shane Vereen",
        "Rank": 137,
        "Position": "RB",
        "Team": "NYG",
        "PosRank": "RB51",
        "Bye": 8,
        "MB": 176,
        "MC": 134,
        "TC": 124,
        "EK": 197,
        "FY": 119,
        "AVG": 150
    },
    {
        "Player": "Sterling Shepard",
        "Rank": 138,
        "Position": "WR",
        "Team": "NYG",
        "PosRank": "WR56",
        "Bye": 8,
        "MB": 184,
        "MC": 111,
        "TC": 116,
        "EK": 172,
        "FY": 169,
        "AVG": 150.4
    },
    {
        "Player": "Marqise Lee",
        "Rank": 139,
        "Position": "WR",
        "Team": "JAC",
        "PosRank": "WR57",
        "Bye": 8,
        "MB": 169,
        "MC": 123,
        "TC": 141,
        "EK": 192,
        "FY": 129,
        "AVG": 150.8
    },
    {
        "Player": "Justin Tucker",
        "Rank": 140,
        "Position": "K",
        "Team": "BAL",
        "PosRank": "K1",
        "Bye": 10,
        "MB": 154,
        "MC": 148,
        "TC": 151,
        "EK": 151,
        "FY": 151,
        "AVG": 151
    },
    {
        "Player": "Philip Rivers",
        "Rank": 141,
        "Position": "QB",
        "Team": "LAC",
        "PosRank": "QB15",
        "Bye": 9,
        "MB": 165,
        "MC": 173,
        "TC": 122,
        "EK": 133,
        "FY": 164,
        "AVG": 151.4
    },
    {
        "Player": "Matt Bryant",
        "Rank": 142,
        "Position": "K",
        "Team": "ATL",
        "PosRank": "K2",
        "Bye": 5,
        "MB": 151,
        "MC": 153,
        "TC": 153,
        "EK": 149,
        "FY": 152,
        "AVG": 151.6
    },
    {
        "Player": "Stephen Gostkowski",
        "Rank": 143,
        "Position": "K",
        "Team": "NE",
        "PosRank": "K3",
        "Bye": 9,
        "MB": 156,
        "MC": 152,
        "TC": 152,
        "EK": 150,
        "FY": 154,
        "AVG": 152.8
    },
    {
        "Player": "Tyrod Taylor",
        "Rank": 144,
        "Position": "QB",
        "Team": "BUF",
        "PosRank": "QB16",
        "Bye": 6,
        "MB": 122,
        "MC": 174,
        "TC": 130,
        "EK": "NR",
        "FY": 139,
        "AVG": 153.2
    },
    {
        "Player": "Adam Vinatieri",
        "Rank": 145,
        "Position": "K",
        "Team": "IND",
        "PosRank": "K4",
        "Bye": 11,
        "MB": 153,
        "MC": 154,
        "TC": 156,
        "EK": 152,
        "FY": 153,
        "AVG": 153.6
    },
    {
        "Player": "Dan Bailey",
        "Rank": 146,
        "Position": "K",
        "Team": "DAL",
        "PosRank": "K5",
        "Bye": 6,
        "MB": 152,
        "MC": 155,
        "TC": 154,
        "EK": 153,
        "FY": 155,
        "AVG": 153.8
    },
    {
        "Player": "Charles Sims",
        "Rank": 147,
        "Position": "RB",
        "Team": "TB",
        "PosRank": "RB52",
        "Bye": 11,
        "MB": "NR",
        "MC": 136,
        "TC": 136,
        "EK": 184,
        "FY": 120,
        "AVG": 155.4
    },
    {
        "Player": "Charcandrick West",
        "Rank": 148,
        "Position": "RB",
        "Team": "KC",
        "PosRank": "RB53",
        "Bye": 10,
        "MB": 116,
        "MC": 179,
        "TC": "NR",
        "EK": 160,
        "FY": 121,
        "AVG": 155.4
    },
    {
        "Player": "Cardinals D/ST",
        "Rank": 149,
        "Position": "DST",
        "Team": "ARI",
        "PosRank": "D/ST6",
        "Bye": 8,
        "MB": 145,
        "MC": "NR",
        "TC": 145,
        "EK": 146,
        "FY": 141,
        "AVG": 155.6
    },
    {
        "Player": "Alvin Kamara",
        "Rank": 150,
        "Position": "RB",
        "Team": "NO",
        "PosRank": "RB54",
        "Bye": 5,
        "MB": 131,
        "MC": 169,
        "TC": 168,
        "EK": 137,
        "FY": 176,
        "AVG": 156.2
    },
    {
        "Player": "Patriots D/ST",
        "Rank": 151,
        "Position": "DST",
        "Team": "NE",
        "PosRank": "D/ST7",
        "Bye": 9,
        "MB": 143,
        "MC": "NR",
        "TC": 149,
        "EK": 143,
        "FY": 148,
        "AVG": 156.8
    },
    {
        "Player": "Matt Prater",
        "Rank": 152,
        "Position": "K",
        "Team": "DET",
        "PosRank": "K6",
        "Bye": 7,
        "MB": 158,
        "MC": 156,
        "TC": 158,
        "EK": 154,
        "FY": 158,
        "AVG": 156.8
    },
    {
        "Player": "Dustin Hopkins",
        "Rank": 153,
        "Position": "K",
        "Team": "WAS",
        "PosRank": "K7",
        "Bye": 5,
        "MB": 157,
        "MC": 159,
        "TC": 157,
        "EK": 158,
        "FY": 157,
        "AVG": 157.6
    },
    {
        "Player": "Torrey Smith",
        "Rank": 154,
        "Position": "WR",
        "Team": "PHI",
        "PosRank": "WR58",
        "Bye": 10,
        "MB": 163,
        "MC": 110,
        "TC": 137,
        "EK": 181,
        "FY": "NR",
        "AVG": 158.4
    },
    {
        "Player": "Eric Ebron",
        "Rank": 155,
        "Position": "TE",
        "Team": "DET",
        "PosRank": "TE13",
        "Bye": 7,
        "MB": 186,
        "MC": 139,
        "TC": 142,
        "EK": "NR",
        "FY": 124,
        "AVG": 158.4
    },
    {
        "Player": "Jeremy Hill",
        "Rank": 156,
        "Position": "RB",
        "Team": "CIN",
        "PosRank": "RB55",
        "Bye": 6,
        "MB": 125,
        "MC": "NR",
        "TC": 184,
        "EK": 120,
        "FY": 172,
        "AVG": 160.4
    },
    {
        "Player": "Kenny Stills",
        "Rank": 157,
        "Position": "WR",
        "Team": "MIA",
        "PosRank": "WR59",
        "Bye": 11,
        "MB": 167,
        "MC": 125,
        "TC": 131,
        "EK": 189,
        "FY": 195,
        "AVG": 161.4
    },
    {
        "Player": "Andy Dalton",
        "Rank": 158,
        "Position": "QB",
        "Team": "CIN",
        "PosRank": "QB17",
        "Bye": 6,
        "MB": 175,
        "MC": 138,
        "TC": 126,
        "EK": "NR",
        "FY": 171,
        "AVG": 162.2
    },
    {
        "Player": "Panthers D/ST",
        "Rank": 159,
        "Position": "DST",
        "Team": "CAR",
        "PosRank": "D/ST8",
        "Bye": 11,
        "MB": 190,
        "MC": 190,
        "TC": 147,
        "EK": 145,
        "FY": 146,
        "AVG": 163.6
    },
    {
        "Player": "D'Onta Foreman",
        "Rank": 160,
        "Position": "RB",
        "Team": "HOU",
        "PosRank": "RB56",
        "Bye": 7,
        "MB": 137,
        "MC": 200,
        "TC": 187,
        "EK": 122,
        "FY": 173,
        "AVG": 163.8
    },
    {
        "Player": "Jason Witten",
        "Rank": 161,
        "Position": "TE",
        "Team": "DAL",
        "PosRank": "TE14",
        "Bye": 6,
        "MB": "NR",
        "MC": 172,
        "TC": 115,
        "EK": "NR",
        "FY": 131,
        "AVG": 164
    },
    {
        "Player": "Mason Crosby",
        "Rank": 162,
        "Position": "K",
        "Team": "GB",
        "PosRank": "K8",
        "Bye": 8,
        "MB": 159,
        "MC": 157,
        "TC": 155,
        "EK": 155,
        "FY": 199,
        "AVG": 165
    },
    {
        "Player": "Carson Wentz",
        "Rank": 163,
        "Position": "QB",
        "Team": "PHI",
        "PosRank": "QB18",
        "Bye": 10,
        "MB": 172,
        "MC": 194,
        "TC": 163,
        "EK": 132,
        "FY": 178,
        "AVG": 167.8
    },
    {
        "Player": "Kendall Wright",
        "Rank": 164,
        "Position": "WR",
        "Team": "CHI",
        "PosRank": "WR60",
        "Bye": 9,
        "MB": 170,
        "MC": "NR",
        "TC": 169,
        "EK": 178,
        "FY": 126,
        "AVG": 168.8
    },
    {
        "Player": "Jaguars D/ST",
        "Rank": 165,
        "Position": "DST",
        "Team": "JAC",
        "PosRank": "D/ST9",
        "Bye": 8,
        "MB": 148,
        "MC": 146,
        "TC": 150,
        "EK": "NR",
        "FY": "NR",
        "AVG": 169.2
    },
    {
        "Player": "Bengals D/ST",
        "Rank": 166,
        "Position": "DST",
        "Team": "CIN",
        "PosRank": "D/ST10",
        "Bye": 6,
        "MB": "NR",
        "MC": 150,
        "TC": 148,
        "EK": 147,
        "FY": "NR",
        "AVG": 169.4
    },
    {
        "Player": "Samaje Perine",
        "Rank": 167,
        "Position": "RB",
        "Team": "WAS",
        "PosRank": "RB57",
        "Bye": 5,
        "MB": 180,
        "MC": 168,
        "TC": 180,
        "EK": 161,
        "FY": 162,
        "AVG": 170.2
    },
    {
        "Player": "Cairo Santos",
        "Rank": 168,
        "Position": "K",
        "Team": "KC",
        "PosRank": "K9",
        "Bye": 10,
        "MB": 191,
        "MC": 191,
        "TC": 160,
        "EK": 156,
        "FY": 160,
        "AVG": 171.6
    },
    {
        "Player": "Robert Woods",
        "Rank": 169,
        "Position": "WR",
        "Team": "LAR",
        "PosRank": "WR61",
        "Bye": 8,
        "MB": 183,
        "MC": 167,
        "TC": 199,
        "EK": 182,
        "FY": 128,
        "AVG": 171.8
    },
    {
        "Player": "Wendell Smallwood",
        "Rank": 170,
        "Position": "RB",
        "Team": "PHI",
        "PosRank": "RB58",
        "Bye": 10,
        "MB": 126,
        "MC": 161,
        "TC": "NR",
        "EK": 198,
        "FY": 174,
        "AVG": 172
    },
    {
        "Player": "Austin Hooper",
        "Rank": 171,
        "Position": "TE",
        "Team": "ATL",
        "PosRank": "TE15",
        "Bye": 5,
        "MB": 162,
        "MC": 171,
        "TC": 166,
        "EK": "NR",
        "FY": 167,
        "AVG": 173.4
    },
    {
        "Player": "DeAndre Washington",
        "Rank": 172,
        "Position": "RB",
        "Team": "OAK",
        "PosRank": "RB59",
        "Bye": 10,
        "MB": 130,
        "MC": 199,
        "TC": "NR",
        "EK": 138,
        "FY": "NR",
        "AVG": 173.8
    },
    {
        "Player": "Jamaal Williams",
        "Rank": 173,
        "Position": "RB",
        "Team": "GB",
        "PosRank": "RB60",
        "Bye": 8,
        "MB": "NR",
        "MC": 128,
        "TC": 175,
        "EK": 164,
        "FY": "NR",
        "AVG": 173.8
    },
    {
        "Player": "Dion Lewis",
        "Rank": 174,
        "Position": "RB",
        "Team": "NE",
        "PosRank": "RB61",
        "Bye": 9,
        "MB": "NR",
        "MC": 176,
        "TC": 181,
        "EK": 124,
        "FY": 193,
        "AVG": 175
    },
    {
        "Player": "Jamaal Charles",
        "Rank": 175,
        "Position": "RB",
        "Team": "DEN",
        "PosRank": "RB62",
        "Bye": 5,
        "MB": 197,
        "MC": 127,
        "TC": 165,
        "EK": 185,
        "FY": "NR",
        "AVG": 175
    },
    {
        "Player": "Cole Beasley",
        "Rank": 176,
        "Position": "WR",
        "Team": "DAL",
        "PosRank": "WR62",
        "Bye": 6,
        "MB": 194,
        "MC": 183,
        "TC": 176,
        "EK": "NR",
        "FY": 122,
        "AVG": 175.2
    },
    {
        "Player": "Tyler Lockett",
        "Rank": 177,
        "Position": "WR",
        "Team": "SEA",
        "PosRank": "WR63",
        "Bye": 6,
        "MB": "NR",
        "MC": 113,
        "TC": 174,
        "EK": 188,
        "FY": "NR",
        "AVG": 175.4
    },
    {
        "Player": "Cooper Kupp",
        "Rank": 178,
        "Position": "WR",
        "Team": "LAR",
        "PosRank": "WR64",
        "Bye": 8,
        "MB": 105,
        "MC": "NR",
        "TC": "NR",
        "EK": 169,
        "FY": "NR",
        "AVG": 175.4
    },
    {
        "Player": "Jalen Richard",
        "Rank": 179,
        "Position": "RB",
        "Team": "OAK",
        "PosRank": "RB63",
        "Bye": 10,
        "MB": 127,
        "MC": "NR",
        "TC": 194,
        "EK": 159,
        "FY": "NR",
        "AVG": 176.4
    },
    {
        "Player": "Mohamed Sanu",
        "Rank": 180,
        "Position": "WR",
        "Team": "ATL",
        "PosRank": "WR65",
        "Bye": 5,
        "MB": 161,
        "MC": 137,
        "TC": 186,
        "EK": "NR",
        "FY": "NR",
        "AVG": 177.2
    },
    {
        "Player": "Giants D/ST",
        "Rank": 181,
        "Position": "DST",
        "Team": "NYG",
        "PosRank": "D/ST11",
        "Bye": 8,
        "MB": "NR",
        "MC": 147,
        "TC": 189,
        "EK": "NR",
        "FY": 150,
        "AVG": 177.6
    },
    {
        "Player": "John Ross",
        "Rank": 182,
        "Position": "WR",
        "Team": "CIN",
        "PosRank": "WR66",
        "Bye": 6,
        "MB": 134,
        "MC": "NR",
        "TC": 183,
        "EK": 174,
        "FY": "NR",
        "AVG": 178.6
    },
    {
        "Player": "Cameron Brate",
        "Rank": 183,
        "Position": "TE",
        "Team": "TB",
        "PosRank": "TE16",
        "Bye": 11,
        "MB": 182,
        "MC": "NR",
        "TC": 185,
        "EK": "NR",
        "FY": 125,
        "AVG": 178.8
    },
    {
        "Player": "Eagles D/ST",
        "Rank": 184,
        "Position": "DST",
        "Team": "PHI",
        "PosRank": "D/ST12",
        "Bye": 10,
        "MB": "NR",
        "MC": 151,
        "TC": "NR",
        "EK": "NR",
        "FY": 145,
        "AVG": 179.8
    },
    {
        "Player": "Devontae Booker",
        "Rank": 185,
        "Position": "RB",
        "Team": "DEN",
        "PosRank": "RB64",
        "Bye": 5,
        "MB": 188,
        "MC": "NR",
        "TC": "NR",
        "EK": 136,
        "FY": 177,
        "AVG": 180.6
    },
    {
        "Player": "Wil Lutz",
        "Rank": 186,
        "Position": "K",
        "Team": "NO",
        "PosRank": "K10",
        "Bye": 5,
        "MB": 155,
        "MC": "NR",
        "TC": 192,
        "EK": "NR",
        "FY": 156,
        "AVG": 181
    },
    {
        "Player": "James Conner",
        "Rank": 187,
        "Position": "RB",
        "Team": "PIT",
        "PosRank": "RB65",
        "Bye": 9,
        "MB": 178,
        "MC": "NR",
        "TC": "NR",
        "EK": 125,
        "FY": "NR",
        "AVG": 181.2
    },
    {
        "Player": "Tim Hightower",
        "Rank": 188,
        "Position": "RB",
        "Team": "SF",
        "PosRank": "RB66",
        "Bye": 11,
        "MB": 139,
        "MC": "NR",
        "TC": "NR",
        "EK": 165,
        "FY": "NR",
        "AVG": 181.4
    },
    {
        "Player": "Taylor Gabriel",
        "Rank": 189,
        "Position": "WR",
        "Team": "ATL",
        "PosRank": "WR67",
        "Bye": 5,
        "MB": "NR",
        "MC": 165,
        "TC": 139,
        "EK": "NR",
        "FY": "NR",
        "AVG": 181.4
    },
    {
        "Player": "Devin Funchess",
        "Rank": 190,
        "Position": "WR",
        "Team": "CAR",
        "PosRank": "WR68",
        "Bye": 11,
        "MB": "NR",
        "MC": 120,
        "TC": 195,
        "EK": 191,
        "FY": "NR",
        "AVG": 181.6
    },
    {
        "Player": "Eli Manning",
        "Rank": 191,
        "Position": "QB",
        "Team": "NYG",
        "PosRank": "QB19",
        "Bye": 8,
        "MB": "NR",
        "MC": 193,
        "TC": 135,
        "EK": "NR",
        "FY": 179,
        "AVG": 181.8
    },
    {
        "Player": "Nelson Agholor",
        "Rank": 192,
        "Position": "WR",
        "Team": "PHI",
        "PosRank": "WR69",
        "Bye": 10,
        "MB": 133,
        "MC": "NR",
        "TC": "NR",
        "EK": 173,
        "FY": "NR",
        "AVG": 181.8
    },
    {
        "Player": "Carson Palmer",
        "Rank": 193,
        "Position": "QB",
        "Team": "ARI",
        "PosRank": "QB20",
        "Bye": 8,
        "MB": 198,
        "MC": 175,
        "TC": 171,
        "EK": "NR",
        "FY": 165,
        "AVG": 182
    },
    {
        "Player": "Chris Boswell",
        "Rank": 194,
        "Position": "K",
        "Team": "PIT",
        "PosRank": "K11",
        "Bye": 9,
        "MB": "NR",
        "MC": 158,
        "TC": 159,
        "EK": "NR",
        "FY": "NR",
        "AVG": 184
    },
    {
        "Player": "J.J. Nelson",
        "Rank": 195,
        "Position": "WR",
        "Team": "ARI",
        "PosRank": "WR70",
        "Bye": 8,
        "MB": 195,
        "MC": 186,
        "TC": 179,
        "EK": 168,
        "FY": 194,
        "AVG": 184.4
    },
    {
        "Player": "Julius Thomas",
        "Rank": 196,
        "Position": "TE",
        "Team": "MIA",
        "PosRank": "TE17",
        "Bye": 11,
        "MB": 166,
        "MC": 178,
        "TC": 196,
        "EK": "NR",
        "FY": 184,
        "AVG": 185
    },
    {
        "Player": "Will Fuller V",
        "Rank": 197,
        "Position": "WR",
        "Team": "HOU",
        "PosRank": "WR71",
        "Bye": 7,
        "MB": "NR",
        "MC": "NR",
        "TC": 129,
        "EK": "NR",
        "FY": "NR",
        "AVG": 186.6
    },
    {
        "Player": "Marlon Mack",
        "Rank": 198,
        "Position": "RB",
        "Team": "IND",
        "PosRank": "RB67",
        "Bye": 11,
        "MB": 164,
        "MC": "NR",
        "TC": "NR",
        "EK": 167,
        "FY": "NR",
        "AVG": 186.8
    },
    {
        "Player": "De'Angelo Henderson",
        "Rank": 199,
        "Position": "RB",
        "Team": "DEN",
        "PosRank": "RB68",
        "Bye": 5,
        "MB": "NR",
        "MC": "NR",
        "TC": "NR",
        "EK": 135,
        "FY": "NR",
        "AVG": 187.8
    },
    {
        "Player": "Breshad Perriman",
        "Rank": 200,
        "Position": "WR",
        "Team": "BAL",
        "PosRank": "WR72",
        "Bye": 10,
        "MB": "NR",
        "MC": 184,
        "TC": 164,
        "EK": 190,
        "FY": "NR",
        "AVG": 188
    }
]

var playerName = "";
var playerPos = "";
var playerTeam = "";
var playerPosRank = "";
var playerBye = "";
var playerRank = "";

for (var i = 0; i < players.length; i++) {

    playerName = players[i].Player;
    playerPos = players[i].Position;
    playerTeam = players[i].Team;
    playerPosRank = players[i].PosRank;
    playerBye = players[i].Bye;
    playerRank = players[i].Rank;



    $("#playerButtons").append("<button class='button btn btn-primary' data-player='" +
        playerName + "' + data-pos='" +
        playerPos + "'>" +
        playerName + "<br>" +
        playerPos + "<br>" +
        playerTeam + "<br>" +
        playerPosRank + "</button>")

};

$("#playerButtons").on("click", ".button", function() {

    playerName = $(this).data("player");
    playerPos = $(this).data("pos");
    $(this).remove();

    console.log(playerPos);

    if (playerPos === 'QB') {
        $("#pickedQB").append("<p class='playerName  text-center'>" + playerName + "</p>");
        $(".playerName").css("text-decoration", "line-through");
        $(".playerName").css("font-size", "18px");

    }
    if (playerPos === 'RB') {
        $("#pickedRB").append("<p class='playerName  text-center'>" + playerName + "</p>");
        $(".playerName").css("text-decoration", "line-through");
        $(".playerName").css("font-size", "18px");

    }
    if (playerPos === 'WR') {
        $("#pickedWR").append("<p class='playerName  text-center'>" + playerName + "</p>");
        $(".playerName").css("text-decoration", "line-through");
        $(".playerName").css("font-size", "18px");

    }
    if (playerPos === 'TE') {
        $("#pickedTE").append("<p class='playerName  text-center'>" + playerName + "</p>");
        $(".playerName").css("text-decoration", "line-through");
        $(".playerName").css("font-size", "18px");

    }
    if (playerPos === 'K' || playerPos === 'DST') {
        $("#pickedKick").append("<p class='playerName  text-center'>" + playerName + "</p>");
        $(".playerName").css("text-decoration", "line-through");
        $(".playerName").css("font-size", "18px");

    }


});